# Generated by Django 3.1 on 2020-09-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='')),
                ('salary', models.CharField(max_length=50)),
            ],
        ),
    ]
